// Load environment variables from .env file
import "dotenv/config";

// Check database connection
// Note: This is optional and can be removed if the database connection
// is not required when starting the application
import "../database/checkConnection";

// Import the Express application from ./app
import app from "./app";

const userPlaylists = {
  href: "https://api.spotify.com/v1/users/smedjan/playlists?offset=1&limit=6&locale=fr,fr-FR;q%3D0.8,en-US;q%3D0.5,en;q%3D0.3",
  limit: 6,
  next: "https://api.spotify.com/v1/users/smedjan/playlists?offset=7&limit=6&locale=fr,fr-FR;q%3D0.8,en-US;q%3D0.5,en;q%3D0.3",
  offset: 1,
  previous:
    "https://api.spotify.com/v1/users/smedjan/playlists?offset=0&limit=6&locale=fr,fr-FR;q%3D0.8,en-US;q%3D0.5,en;q%3D0.3",
  total: 98,
  items: [
    {
      collaborative: false,
      description:
        'A mish mash of a bunch of songs that you can maybe dance to. Curated by <a href="https://twitter.com/nicktoumpelis">Nick Toumpelis</a>. Photography by <a href="https://www.instagram.com/nicktoumpelis/">Nick Toumpelis</a>. ',
      external_urls: {
        spotify: "https://open.spotify.com/playlist/3tT3E3Q4u5Xd0v3ySPLR1O",
      },
      href: "https://api.spotify.com/v1/playlists/3tT3E3Q4u5Xd0v3ySPLR1O",
      id: "3tT3E3Q4u5Xd0v3ySPLR1O",
      images: [
        {
          height: null,
          url: "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84f8496493a06aec2c3eda1a42",
          width: null,
        },
      ],
      name: "dance fusion",
      owner: {
        display_name: "Nick Toumpelis",
        external_urls: {
          spotify: "https://open.spotify.com/user/1226836970",
        },
        href: "https://api.spotify.com/v1/users/1226836970",
        id: "1226836970",
        type: "user",
        uri: "spotify:user:1226836970",
      },
      primary_color: null,
      public: true,
      snapshot_id: "AAAN3eephAMj/tM4sCQtXXGRL39TnfyI",
      tracks: {
        href: "https://api.spotify.com/v1/playlists/3tT3E3Q4u5Xd0v3ySPLR1O/tracks",
        total: 22,
      },
      type: "playlist",
      uri: "spotify:playlist:3tT3E3Q4u5Xd0v3ySPLR1O",
    },
    {
      collaborative: false,
      description: "",
      external_urls: {
        spotify: "https://open.spotify.com/playlist/41R1UENL6yUDiRR2riptb7",
      },
      href: "https://api.spotify.com/v1/playlists/41R1UENL6yUDiRR2riptb7",
      id: "41R1UENL6yUDiRR2riptb7",
      images: [
        {
          height: 640,
          url: "https://mosaic.scdn.co/640/ab67616d00001e02087ae01edc17b3fbe0f44b28ab67616d00001e02722ee6054732c347e335cb35ab67616d00001e027d4287bed60bfc5f13d96644ab67616d00001e02bef76218c65153abaed75e6e",
          width: 640,
        },
        {
          height: 300,
          url: "https://mosaic.scdn.co/300/ab67616d00001e02087ae01edc17b3fbe0f44b28ab67616d00001e02722ee6054732c347e335cb35ab67616d00001e027d4287bed60bfc5f13d96644ab67616d00001e02bef76218c65153abaed75e6e",
          width: 300,
        },
        {
          height: 60,
          url: "https://mosaic.scdn.co/60/ab67616d00001e02087ae01edc17b3fbe0f44b28ab67616d00001e02722ee6054732c347e335cb35ab67616d00001e027d4287bed60bfc5f13d96644ab67616d00001e02bef76218c65153abaed75e6e",
          width: 60,
        },
      ],
      name: "covers and under covers",
      owner: {
        display_name: "migo",
        external_urls: {
          spotify: "https://open.spotify.com/user/migo",
        },
        href: "https://api.spotify.com/v1/users/migo",
        id: "migo",
        type: "user",
        uri: "spotify:user:migo",
      },
      primary_color: null,
      public: true,
      snapshot_id: "AAAAIrLzEpQV6o/ItxCn5yAsgFr+fegH",
      tracks: {
        href: "https://api.spotify.com/v1/playlists/41R1UENL6yUDiRR2riptb7/tracks",
        total: 21,
      },
      type: "playlist",
      uri: "spotify:playlist:41R1UENL6yUDiRR2riptb7",
    },
    {
      collaborative: false,
      description: "Bombastic tunes -- in some way or another",
      external_urls: {
        spotify: "https://open.spotify.com/playlist/6dSh5StaaE1XbIF5s7Lxng",
      },
      href: "https://api.spotify.com/v1/playlists/6dSh5StaaE1XbIF5s7Lxng",
      id: "6dSh5StaaE1XbIF5s7Lxng",
      images: [
        {
          height: 640,
          url: "https://mosaic.scdn.co/640/ab67616d00001e020dd350beeb5ac73672ad6e80ab67616d00001e02341b1e5f0395b17821491c7dab67616d00001e024ccb64f022a53d3e8ec84a20ab67616d00001e02e477610ef54781d751a9e319",
          width: 640,
        },
        {
          height: 300,
          url: "https://mosaic.scdn.co/300/ab67616d00001e020dd350beeb5ac73672ad6e80ab67616d00001e02341b1e5f0395b17821491c7dab67616d00001e024ccb64f022a53d3e8ec84a20ab67616d00001e02e477610ef54781d751a9e319",
          width: 300,
        },
        {
          height: 60,
          url: "https://mosaic.scdn.co/60/ab67616d00001e020dd350beeb5ac73672ad6e80ab67616d00001e02341b1e5f0395b17821491c7dab67616d00001e024ccb64f022a53d3e8ec84a20ab67616d00001e02e477610ef54781d751a9e319",
          width: 60,
        },
      ],
      name: "Fläskiga låtar",
      owner: {
        display_name: "migo",
        external_urls: {
          spotify: "https://open.spotify.com/user/migo",
        },
        href: "https://api.spotify.com/v1/users/migo",
        id: "migo",
        type: "user",
        uri: "spotify:user:migo",
      },
      primary_color: null,
      public: true,
      snapshot_id: "AAABDR+cig8lZhZCDMyEdhX8v8t8Pb6r",
      tracks: {
        href: "https://api.spotify.com/v1/playlists/6dSh5StaaE1XbIF5s7Lxng/tracks",
        total: 44,
      },
      type: "playlist",
      uri: "spotify:playlist:6dSh5StaaE1XbIF5s7Lxng",
    },
    {
      collaborative: false,
      description: "Migo",
      external_urls: {
        spotify: "https://open.spotify.com/playlist/6hBpet9cW4cVgn96xBJ5Ay",
      },
      href: "https://api.spotify.com/v1/playlists/6hBpet9cW4cVgn96xBJ5Ay",
      id: "6hBpet9cW4cVgn96xBJ5Ay",
      images: [
        {
          height: 640,
          url: "https://mosaic.scdn.co/640/ab67616d00001e021a0e01b6cd607bbc41c3ff4bab67616d00001e02578f1ac435ac326e48334f66ab67616d00001e02722ee6054732c347e335cb35ab67616d00001e02e477610ef54781d751a9e319",
          width: 640,
        },
        {
          height: 300,
          url: "https://mosaic.scdn.co/300/ab67616d00001e021a0e01b6cd607bbc41c3ff4bab67616d00001e02578f1ac435ac326e48334f66ab67616d00001e02722ee6054732c347e335cb35ab67616d00001e02e477610ef54781d751a9e319",
          width: 300,
        },
        {
          height: 60,
          url: "https://mosaic.scdn.co/60/ab67616d00001e021a0e01b6cd607bbc41c3ff4bab67616d00001e02578f1ac435ac326e48334f66ab67616d00001e02722ee6054732c347e335cb35ab67616d00001e02e477610ef54781d751a9e319",
          width: 60,
        },
      ],
      name: "migo1",
      owner: {
        display_name: "migo",
        external_urls: {
          spotify: "https://open.spotify.com/user/migo",
        },
        href: "https://api.spotify.com/v1/users/migo",
        id: "migo",
        type: "user",
        uri: "spotify:user:migo",
      },
      primary_color: null,
      public: true,
      snapshot_id: "AAAAbUWFczxCb7xWrXTgRM3XWd/LZXBy",
      tracks: {
        href: "https://api.spotify.com/v1/playlists/6hBpet9cW4cVgn96xBJ5Ay/tracks",
        total: 66,
      },
      type: "playlist",
      uri: "spotify:playlist:6hBpet9cW4cVgn96xBJ5Ay",
    },
    {
      collaborative: false,
      description: "",
      external_urls: {
        spotify: "https://open.spotify.com/playlist/47s8Pj6MjV5UWYEaHIe9ZH",
      },
      href: "https://api.spotify.com/v1/playlists/47s8Pj6MjV5UWYEaHIe9ZH",
      id: "47s8Pj6MjV5UWYEaHIe9ZH",
      images: [
        {
          height: 640,
          url: "https://mosaic.scdn.co/640/ab67616d00001e023a2d2b9621ef645380c63c16ab67616d00001e02ba4c798ab356b8adb64bb2fcab67616d00001e02ba6132f887666a2627eb8a56ab67616d00001e02dbe9c4609ec382dcc0391e62",
          width: 640,
        },
        {
          height: 300,
          url: "https://mosaic.scdn.co/300/ab67616d00001e023a2d2b9621ef645380c63c16ab67616d00001e02ba4c798ab356b8adb64bb2fcab67616d00001e02ba6132f887666a2627eb8a56ab67616d00001e02dbe9c4609ec382dcc0391e62",
          width: 300,
        },
        {
          height: 60,
          url: "https://mosaic.scdn.co/60/ab67616d00001e023a2d2b9621ef645380c63c16ab67616d00001e02ba4c798ab356b8adb64bb2fcab67616d00001e02ba6132f887666a2627eb8a56ab67616d00001e02dbe9c4609ec382dcc0391e62",
          width: 60,
        },
      ],
      name: "Dance I Said",
      owner: {
        display_name: "Michelle Kadir",
        external_urls: {
          spotify: "https://open.spotify.com/user/michellekadir",
        },
        href: "https://api.spotify.com/v1/users/michellekadir",
        id: "michellekadir",
        type: "user",
        uri: "spotify:user:michellekadir",
      },
      primary_color: null,
      public: true,
      snapshot_id: "AAACj+vJmuuu9qF+sfuRAF4/DobgjK9A",
      tracks: {
        href: "https://api.spotify.com/v1/playlists/47s8Pj6MjV5UWYEaHIe9ZH/tracks",
        total: 106,
      },
      type: "playlist",
      uri: "spotify:playlist:47s8Pj6MjV5UWYEaHIe9ZH",
    },
    {
      collaborative: false,
      description: "",
      external_urls: {
        spotify: "https://open.spotify.com/playlist/13XT3kKAKOuhKV1IdgQxzf",
      },
      href: "https://api.spotify.com/v1/playlists/13XT3kKAKOuhKV1IdgQxzf",
      id: "13XT3kKAKOuhKV1IdgQxzf",
      images: [
        {
          height: 640,
          url: "https://mosaic.scdn.co/640/ab67616d00001e0242165edf668b41cb531722b0ab67616d00001e02599dfe976032830e5ec68945ab67616d00001e0297a9ac8888b636959cd8353cab67616d00001e029d2ff3fc2590549e13f17670",
          width: 640,
        },
        {
          height: 300,
          url: "https://mosaic.scdn.co/300/ab67616d00001e0242165edf668b41cb531722b0ab67616d00001e02599dfe976032830e5ec68945ab67616d00001e0297a9ac8888b636959cd8353cab67616d00001e029d2ff3fc2590549e13f17670",
          width: 300,
        },
        {
          height: 60,
          url: "https://mosaic.scdn.co/60/ab67616d00001e0242165edf668b41cb531722b0ab67616d00001e02599dfe976032830e5ec68945ab67616d00001e0297a9ac8888b636959cd8353cab67616d00001e029d2ff3fc2590549e13f17670",
          width: 60,
        },
      ],
      name: "Instrumental",
      owner: {
        display_name: "migo",
        external_urls: {
          spotify: "https://open.spotify.com/user/migo",
        },
        href: "https://api.spotify.com/v1/users/migo",
        id: "migo",
        type: "user",
        uri: "spotify:user:migo",
      },
      primary_color: null,
      public: true,
      snapshot_id: "AAAAWIMuC6bnXv1rYnZ7JKx21qOoOGOc",
      tracks: {
        href: "https://api.spotify.com/v1/playlists/13XT3kKAKOuhKV1IdgQxzf/tracks",
        total: 56,
      },
      type: "playlist",
      uri: "spotify:playlist:13XT3kKAKOuhKV1IdgQxzf",
    },
  ],
};

app.get("/api/userPlaylists", (req, res, next) => {
  res.json(userPlaylists);
});

// PODCASTS

const userPodcasts = {
  href: "https://api.spotify.com/v1/me/episodes?offset=0&limit=5&locale=fr,fr-FR;q%3D0.8,en-US;q%3D0.5,en;q%3D0.3",
  limit: 5,
  next: null,
  offset: 0,
  previous: null,
  total: 5,
  items: [
    {
      added_at: "2024-11-14T12:51:41Z",
      episode: {
        audio_preview_url:
          "https://podz-content.spotifycdn.com/audio/clips/5B9g8Q0CO57npnXZt7r3Sz/clip_549833_609833.mp3",
        description:
          "Le 7 juillet 2017 à Toulouse, la jeune Cintia Lunimbu est découverte chez elle, baignant dans une mare de sang. Elle a été égorgée. Autour d’elle, tout a été fouillé… S’agit-il d’un cambriolage qui a mal tourné ? Face à la violence du crime, les policiers s’interrogent. Ne serait-ce pas plutôt un crime passionnel ou une vengeance personnelle ? Pour les proches de Cintia, ces hypothèses n’ont aucun sens. Mais alors, qui aurait pu vouloir sa mort ? Ce que tous ignorent encore, c’est que cette enquête va les plonger plus de 40 ans en arrière, au cœur d’une des affaires judiciaires les plus retentissantes que la France ait jamais connu. L’affaire Jean-Baptiste Rambla, un podcast inédit de Chroniques Criminelles, raconté par Jacques Pradel. ",
        duration_ms: 3471288,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/episode/5j9kS6IY8Pmr5ogvOxvodp",
        },
        href: "https://api.spotify.com/v1/episodes/5j9kS6IY8Pmr5ogvOxvodp",
        html_description:
          "<p>Le 7 juillet 2017 à Toulouse, la jeune Cintia Lunimbu est découverte chez elle, baignant dans une mare de sang. Elle a été égorgée. Autour d’elle, tout a été fouillé… S’agit-il d’un cambriolage qui a mal tourné ? Face à la violence du crime, les policiers s’interrogent. Ne serait-ce pas plutôt un crime passionnel ou une vengeance personnelle ? Pour les proches de Cintia, ces hypothèses n’ont aucun sens. Mais alors, qui aurait pu vouloir sa mort ? Ce que tous ignorent encore, c’est que cette enquête va les plonger plus de 40 ans en arrière, au cœur d’une des affaires judiciaires les plus retentissantes que la France ait jamais connu. L’affaire Jean-Baptiste Rambla, un podcast inédit de Chroniques Criminelles, raconté par Jacques Pradel. </p>",
        id: "5j9kS6IY8Pmr5ogvOxvodp",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8ad17fbf316cbe8bfd5445a53e",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1fd17fbf316cbe8bfd5445a53e",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68dd17fbf316cbe8bfd5445a53e",
            width: 64,
          },
        ],
        is_externally_hosted: false,
        is_playable: true,
        language: "fr",
        languages: ["fr"],
        name: "L’affaire Jean-Baptiste Rambla : Le crime en héritage",
        release_date: "2024-11-13",
        release_date_precision: "day",
        resume_point: {
          fully_played: false,
          resume_position_ms: 0,
        },
        show: {
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          copyrights: [],
          description:
            "Disparitions inquiétantes, crimes passionnels,  ou machinations diaboliques… Découvrez les secrets des faits-divers les plus marquants. Tueurs en série, amants démoniaques, tous pensaient avoir commis le crime parfait. Mais tous, sont aujourd’hui derrière les barreaux. Qui sont ces meurtriers ? Et comment les policiers sont-ils parvenus à les confondre ? La découverte de la vérité ne tient parfois qu’à un fil… Grâce aux témoignages de tous les protagonistes, des enquêteurs aux familles des victimes, Jacques Pradel vous fait revivre ces enquêtes incroyables, riches en rebondissements… et en émotions… Retrouvez le Podcast Chroniques Criminelles, et plongez au cœur des  affaires les plus étonnantes de l’histoire judiciaire. Un podcast du Groupe TF1.         ",
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/show/1Tn0rNAr68DU0gLZXWiptV",
          },
          href: "https://api.spotify.com/v1/shows/1Tn0rNAr68DU0gLZXWiptV",
          html_description:
            "<p>Disparitions inquiétantes, crimes passionnels,  ou machinations diaboliques… Découvrez les secrets des faits-divers les plus marquants. Tueurs en série, amants démoniaques, tous pensaient avoir commis le crime parfait. Mais tous, sont aujourd’hui derrière les barreaux. Qui sont ces meurtriers ? Et comment les policiers sont-ils parvenus à les confondre ? La découverte de la vérité ne tient parfois qu’à un fil… Grâce aux témoignages de tous les protagonistes, des enquêteurs aux familles des victimes, Jacques Pradel vous fait revivre ces enquêtes incroyables, riches en rebondissements… et en émotions… Retrouvez le Podcast Chroniques Criminelles, et plongez au cœur des  affaires les plus étonnantes de l’histoire judiciaire. Un podcast du Groupe TF1.         </p>",
          id: "1Tn0rNAr68DU0gLZXWiptV",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab6765630000ba8ad17fbf316cbe8bfd5445a53e",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67656300005f1fd17fbf316cbe8bfd5445a53e",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab6765630000f68dd17fbf316cbe8bfd5445a53e",
              width: 64,
            },
          ],
          is_externally_hosted: false,
          languages: ["fr"],
          media_type: "audio",
          name: "CHRONIQUES CRIMINELLES",
          publisher: "Jacques Pradel - TF1",
          total_episodes: 121,
          type: "show",
          uri: "spotify:show:1Tn0rNAr68DU0gLZXWiptV",
        },
        type: "episode",
        uri: "spotify:episode:5j9kS6IY8Pmr5ogvOxvodp",
      },
    },
    {
      added_at: "2024-11-14T12:51:31Z",
      episode: {
        audio_preview_url:
          "https://podz-content.spotifycdn.com/audio/clips/60qj48s8zL34XyPnoUG6On/clip_0_60000.mp3",
        description:
          "Chaque jour, en moins de 10 minutes, un résumé de l’actualité du jour. Rapide, facile, accessible.📺 Pour découvrir et vous abonner à notre chaine YouTube \"Grands Formats\" (interviews, enquêtes, reportages) : https://www.youtube.com/@hugodecryptegrandsformats💼 Pour trouver un stage, alternance ou CDD/CDI : https://jobs.hugodecrypte.com/🗞️ L'essentiel de l'actualité, gratuitement, par email : https://inscription.kessel.media/hugodecrypteEt pour suivre l'actualité sur Instagram : https://instagram.com/hugodecrypte🔗 DES LIENS POUR EN SAVOIR PLUSBITCOIN TRUMP : Capital, Ouest-France, Les Echos, TimeISRAËL - GAZA : Sud-Ouest, Le Huffpost, France 24INONDATIONS ESPAGNE : Le Figaro, Franceinfo RODRIGUE PETITOT MARTINIQUE : Le Monde, 20 MinutesSÉCHERESSE GUYANE : Franceinfo, France Guyane CARNET DE SANTÉ : Le Parisien, Franceinfo PATRONS CAC 40 : Franceinfo, RTLEMERAUDE ENCHÈRES : BFMTV, Sud-Ouest Écriture : Blanche Vathonne - Léah Boukobza - Lisa Impératrice - Hugo Travers  Hébergé par Acast. Visitez acast.com/privacy pour plus d'informations.",
        duration_ms: 806269,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/episode/2FAEgwgJ4sH5qy0fFee3uz",
        },
        href: "https://api.spotify.com/v1/episodes/2FAEgwgJ4sH5qy0fFee3uz",
        html_description:
          '<p>Chaque jour, en moins de 10 minutes, un résumé de l’actualité du jour. Rapide, facile, accessible.</p><p>&#x1f4fa; Pour découvrir et vous abonner à notre chaine YouTube &#34;Grands Formats&#34; (interviews, enquêtes, reportages) : https://www.youtube.com/&#64;hugodecryptegrandsformats</p><p>&#x1f4bc; Pour trouver un stage, alternance ou CDD/CDI : https://jobs.hugodecrypte.com/</p><p>&#x1f5de;️ L&#39;essentiel de l&#39;actualité, gratuitement, par email : https://inscription.kessel.media/hugodecrypte</p><p>Et pour suivre l&#39;actualité sur Instagram : https://instagram.com/hugodecrypte</p><br /><p>&#x1f517; DES LIENS POUR EN SAVOIR PLUS</p><br /><p>BITCOIN TRUMP : <a href="https://hugodecry.pt/04emff" rel="nofollow">Capital</a>, <a href="https://hugodecry.pt/847plu" rel="nofollow">Ouest-France</a>, <a href="https://hugodecry.pt/czsqxd" rel="nofollow">Les Echos</a>, <a href="https://hugodecry.pt/0w5tme" rel="nofollow">Time</a></p><br /><p>ISRAËL - GAZA : <a href="https://hugodecry.pt/vma470" rel="nofollow">Sud-Ouest</a>, <a href="https://hugodecry.pt/csb7w5" rel="nofollow">Le Huffpost</a>, <a href="https://hugodecry.pt/4xwkh2" rel="nofollow">France 24</a></p><br /><p>INONDATIONS ESPAGNE : <a href="https://hugodecry.pt/uzyd8s" rel="nofollow">Le Figaro</a>, <a href="https://hugodecry.pt/95ouqq" rel="nofollow">Franceinfo</a> </p><br /><p>RODRIGUE PETITOT MARTINIQUE : <a href="https://hugodecry.pt/g3mtp5" rel="nofollow">Le Monde</a>, <a href="https://hugodecry.pt/nefkk5" rel="nofollow">20 Minutes</a></p><br /><p>SÉCHERESSE GUYANE : <a href="https://hugodecry.pt/0zgjgo" rel="nofollow">Franceinfo</a>, <a href="https://hugodecry.pt/uuippd" rel="nofollow">France Guyane</a> </p><br /><p>CARNET DE SANTÉ : <a href="https://hugodecry.pt/n3atu1" rel="nofollow">Le Parisien</a>, <a href="https://hugodecry.pt/c378he" rel="nofollow">Franceinfo</a> </p><br /><p>PATRONS CAC 40 : <a href="https://hugodecry.pt/j2vqnw" rel="nofollow">Franceinfo</a>, <a href="https://hugodecry.pt/ead2hg" rel="nofollow">RTL</a></p><br /><p>EMERAUDE ENCHÈRES : <a href="https://hugodecry.pt/32kewa" rel="nofollow">BFMTV</a>, <a href="https://hugodecry.pt/a65e5v" rel="nofollow">Sud-Ouest</a> </p><br /><p><br /></p><br /><p><br /></p><p>Écriture : Blanche Vathonne - Léah Boukobza - Lisa Impératrice - Hugo Travers </p><br /><p> Hébergé par Acast. Visitez <a href="https://acast.com/privacy" rel="nofollow">acast.com/privacy</a> pour plus d&#39;informations.</p>',
        id: "2FAEgwgJ4sH5qy0fFee3uz",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8a4f119cac9bb6575c25e428ab",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1f4f119cac9bb6575c25e428ab",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68d4f119cac9bb6575c25e428ab",
            width: 64,
          },
        ],
        is_externally_hosted: false,
        is_playable: true,
        language: "fr",
        languages: ["fr"],
        name: "Pourquoi Donald Trump fait bondir le bitcoin",
        release_date: "2024-11-13",
        release_date_precision: "day",
        resume_point: {
          fully_played: false,
          resume_position_ms: 0,
        },
        show: {
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          copyrights: [],
          description:
            "Chaque jour, retrouvez l'actu résumée et expliquée en dix minutes, par HugoDécrypte. Hébergé par Acast. Visitez acast.com/privacy pour plus d'informations.",
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/show/6y1PloEyNsCNJH9vHias4T",
          },
          href: "https://api.spotify.com/v1/shows/6y1PloEyNsCNJH9vHias4T",
          html_description:
            'Chaque jour, retrouvez l&#39;actu résumée et expliquée en dix minutes, par HugoDécrypte.<br /><p> Hébergé par Acast. Visitez <a href="https://acast.com/privacy" rel="nofollow">acast.com/privacy</a> pour plus d&#39;informations.</p>',
          id: "6y1PloEyNsCNJH9vHias4T",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab6765630000ba8a4f119cac9bb6575c25e428ab",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67656300005f1f4f119cac9bb6575c25e428ab",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab6765630000f68d4f119cac9bb6575c25e428ab",
              width: 64,
            },
          ],
          is_externally_hosted: false,
          languages: ["fr"],
          media_type: "audio",
          name: "Les actus du jour - Hugo Décrypte",
          publisher: "Hugo Décrypte",
          total_episodes: 960,
          type: "show",
          uri: "spotify:show:6y1PloEyNsCNJH9vHias4T",
        },
        type: "episode",
        uri: "spotify:episode:2FAEgwgJ4sH5qy0fFee3uz",
      },
    },
    {
      added_at: "2024-11-14T12:51:23Z",
      episode: {
        audio_preview_url:
          "https://podz-content.spotifycdn.com/audio/clips/1po13Wx2G7L5YQS38wB8Et/clip_323900_385700.mp3",
        description:
          "⭐ Learn English through story! ⭐ Enjoy this high B1 - B2 British English story for learning English. This short intermediate level 5 - level 6 English story is about a beautiful old English house called Rosewood Manor.   📝 Visit the Lovely English Stories Store and use code YOUTUBE10 to get 10% off your productivity pack or English phrasal verbs story: https://www.etsy.com/uk/shop/LovelyEnglishStories   ",
        duration_ms: 585061,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/episode/7AmJ4Aa0E6GAupzQyppJJi",
        },
        href: "https://api.spotify.com/v1/episodes/7AmJ4Aa0E6GAupzQyppJJi",
        html_description:
          '<p>⭐ Learn English through story! ⭐ Enjoy this high B1 - B2 British English story for learning English. This short intermediate level 5 - level 6 English story is about a beautiful old English house called Rosewood Manor. <br/>&#x1f4dd; Visit the Lovely English Stories Store and use code YOUTUBE10 to get 10% off your productivity pack or English phrasal verbs story: <a href="https://www.etsy.com/uk/shop/LovelyEnglishStories" rel="nofollow">https://www.etsy.com/uk/shop/LovelyEnglishStories </a><br/></p>',
        id: "7AmJ4Aa0E6GAupzQyppJJi",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8aa756875ae930eded58b09769",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1fa756875ae930eded58b09769",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68da756875ae930eded58b09769",
            width: 64,
          },
        ],
        is_externally_hosted: false,
        is_playable: true,
        language: "en-GB",
        languages: ["en-GB"],
        name: "Rosewood Manor - B1 - B2 English Story for Learning English",
        release_date: "2023-08-01",
        release_date_precision: "day",
        resume_point: {
          fully_played: false,
          resume_position_ms: 0,
        },
        show: {
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          copyrights: [],
          description:
            "Welcome to Lovely English Stories where you can learn British English through story. We produce original British English stories for beginner, intermediate and advanced English students. Our stories and videos are created by qualified teachers and are ideal for English listening, pronunciation and reading practise.   Visit us on YouTube: https://www.youtube.com/c/lovelyenglishstories",
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/show/6jpbkFJUJbhp7Es6BPBJio",
          },
          href: "https://api.spotify.com/v1/shows/6jpbkFJUJbhp7Es6BPBJio",
          html_description:
            "Welcome to Lovely English Stories where you can learn British English through story. We produce original British English stories for beginner, intermediate and advanced English students. Our stories and videos are created by qualified teachers and are ideal for English listening, pronunciation and reading practise. <br/><br /><br/>Visit us on YouTube: https://www.youtube.com/c/lovelyenglishstories",
          id: "6jpbkFJUJbhp7Es6BPBJio",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab6765630000ba8aa756875ae930eded58b09769",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67656300005f1fa756875ae930eded58b09769",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab6765630000f68da756875ae930eded58b09769",
              width: 64,
            },
          ],
          is_externally_hosted: false,
          languages: ["en-GB"],
          media_type: "mixed",
          name: "Lovely English Stories",
          publisher: "Lovely English Stories",
          total_episodes: 164,
          type: "show",
          uri: "spotify:show:6jpbkFJUJbhp7Es6BPBJio",
        },
        type: "episode",
        uri: "spotify:episode:7AmJ4Aa0E6GAupzQyppJJi",
      },
    },
    {
      added_at: "2024-11-14T12:51:16Z",
      episode: {
        audio_preview_url:
          "https://podz-content.spotifycdn.com/audio/clips/0fJNjYmN2IQkPAqY0g8c97/clip_0_60000.mp3",
        description:
          "Le matin des ides de mars de l'an -44, le dictateur romain Jules César est victime d'un complot, il est brutalement assassiné de 23 coups de poignards. Ce récit est à découvrir dans ce nouvel épisode, n'hésitez pas à l'écouter et à vous abonner à Perles d'Histoire (en activant les notifications) !L'image de couverture et un extrait sonore viennent de l'excellent jeu Assassin's Creed Origins, des courts extraits sont tirés également de Gladiator, Kaamelott et Rome.Un podcast du Studio Biloba, présenté par Gabriel Macé. Hébergé par Acast. Visitez acast.com/privacy pour plus d'informations.",
        duration_ms: 631092,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/episode/7g8BKC9vAhlLndIeivlsab",
        },
        href: "https://api.spotify.com/v1/episodes/7g8BKC9vAhlLndIeivlsab",
        html_description:
          '<p>Le matin des ides de mars de l&#39;an -44, le dictateur romain Jules César est victime d&#39;un complot, il est brutalement assassiné de 23 coups de poignards. Ce récit est à découvrir dans ce nouvel épisode, n&#39;hésitez pas à l&#39;écouter et à vous abonner à Perles d&#39;Histoire (en activant les notifications) !</p><p>L&#39;image de couverture et un extrait sonore viennent de l&#39;excellent jeu Assassin&#39;s Creed Origins, des courts extraits sont tirés également de Gladiator, Kaamelott et Rome.</p><p>Un podcast du <a href="https://studiobiloba.fr/" rel="nofollow">Studio Biloba</a>, présenté par <a href="https://twitter.com/gab_mace" rel="nofollow">Gabriel Macé</a>.</p><br /><p> Hébergé par Acast. Visitez <a href="https://acast.com/privacy" rel="nofollow">acast.com/privacy</a> pour plus d&#39;informations.</p>',
        id: "7g8BKC9vAhlLndIeivlsab",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8aaf6eeb134c7a3cb58eb6e508",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1faf6eeb134c7a3cb58eb6e508",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68daf6eeb134c7a3cb58eb6e508",
            width: 64,
          },
        ],
        is_externally_hosted: false,
        is_playable: true,
        language: "fr",
        languages: ["fr"],
        name: "-44 : Jules César est assassiné !",
        release_date: "2021-06-01",
        release_date_precision: "day",
        resume_point: {
          fully_played: false,
          resume_position_ms: 0,
        },
        show: {
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          copyrights: [],
          description:
            "Un podcast immersif pour découvrir chaque mois une nouvelle anecdote surprenante, croustillante et toujours passionnante de l'Histoire. Que vous soyez fan des récits de Nota Bene, de Franck Ferrand, de Richard Fremder ou encore de Stéphane Bern, laissez-vous tenter, écoutez quelques Perles d'Histoire (c'est l'ancien nom du podcast) et abonnez-vous ! Hébergé par Acast. Visitez acast.com/privacy pour plus d'informations.",
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/show/5Ri0vMjsVAa6CWzLrKgUTx",
          },
          href: "https://api.spotify.com/v1/shows/5Ri0vMjsVAa6CWzLrKgUTx",
          html_description:
            'Un podcast immersif pour découvrir chaque mois une nouvelle anecdote surprenante, croustillante et toujours passionnante de l&#39;Histoire. Que vous soyez fan des récits de Nota Bene, de Franck Ferrand, de Richard Fremder ou encore de Stéphane Bern, laissez-vous tenter, écoutez quelques Perles d&#39;Histoire (c&#39;est l&#39;ancien nom du podcast) et abonnez-vous !<br /><p> Hébergé par Acast. Visitez <a href="https://acast.com/privacy" rel="nofollow">acast.com/privacy</a> pour plus d&#39;informations.</p>',
          id: "5Ri0vMjsVAa6CWzLrKgUTx",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab6765630000ba8a7171a32a1209774e5fe558fc",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67656300005f1f7171a32a1209774e5fe558fc",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab6765630000f68d7171a32a1209774e5fe558fc",
              width: 64,
            },
          ],
          is_externally_hosted: false,
          languages: ["fr"],
          media_type: "audio",
          name: "Pépites d'Histoire",
          publisher: "Studio Biloba",
          total_episodes: 66,
          type: "show",
          uri: "spotify:show:5Ri0vMjsVAa6CWzLrKgUTx",
        },
        type: "episode",
        uri: "spotify:episode:7g8BKC9vAhlLndIeivlsab",
      },
    },
    {
      added_at: "2024-11-14T12:50:51Z",
      episode: {
        audio_preview_url:
          "https://podz-content.spotifycdn.com/audio/clips/2LHbVEsrpl1a0kowmFfCYR/clip_269392_329392.mp3",
        description:
          'Est-ce l’échec d’une femme politique ou d’un parti tout entier ? Largement battue par son rival Donald Trump, la démocrate Kamala Harris a échoué à devenir la première femme présidente des Etats-Unis.Le candidat républicain a en effet été élu avec une large avance, remportant les sept swing states, les Etats-clés où se jouait l’élection. Et même dans leurs bastions historiques, les démocrates ont obtenu des chiffres décevants, voire désastreux. A New York, Kamala Harris a réalisé le pire score de ce parti depuis plus de trente ans.Comment expliquer cette débâcle ? Kamala Harris doit-elle porter seule le poids de la défaite ? Ou bien la vague rouge en faveur de Donald Trump aurait-elle triomphé de n’importe quel candidat démocrate ? Dans cet épisode du podcast « L’Heure du Monde », Piotr Smolar, le correspondant du Monde à Washington, répond à toutes ces questions.Un épisode d’Adélaïde Tenaglia et Claire Leys. Réalisation : Amandine Robillard. Présentation et rédaction en chef : Jean-Guillaume Santi. Dans cet épisode : extraits du débat télévisé entre Kamala Harris et Donald Trump le 10 septembre 2024. Cet épisode a été publié le 14 novembre 2024.---Pour soutenir "L\'Heure du Monde" et notre rédaction, abonnez-vous sur abopodcast.lemonde.fr Hébergé par Audion. Visitez https://www.audion.fm/fr/privacy-policy pour plus d’informations.',
        duration_ms: 1601201,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/episode/5p6v3tAQlnOoGwZzQ2nUVw",
        },
        href: "https://api.spotify.com/v1/episodes/5p6v3tAQlnOoGwZzQ2nUVw",
        html_description:
          '<p>Est-ce l’échec d’une femme politique ou d’un parti tout entier ? Largement battue par son rival Donald Trump, la démocrate Kamala Harris a échoué à devenir la première femme présidente des Etats-Unis.<br /><br />Le candidat républicain a en effet été élu avec une large avance, remportant les sept swing states, les Etats-clés où se jouait l’élection. Et même dans leurs bastions historiques, les démocrates ont obtenu des chiffres décevants, voire désastreux. A New York, Kamala Harris a réalisé le pire score de ce parti depuis plus de trente ans.<br /><br />Comment expliquer cette débâcle ? Kamala Harris doit-elle porter seule le poids de la défaite ? Ou bien la vague rouge en faveur de Donald Trump aurait-elle triomphé de n’importe quel candidat démocrate ? Dans cet épisode du podcast « L’Heure du Monde », Piotr Smolar, le correspondant du Monde à Washington, répond à toutes ces questions.<br /><br />Un épisode d’Adélaïde Tenaglia et Claire Leys. Réalisation : Amandine Robillard. Présentation et rédaction en chef : Jean-Guillaume Santi. Dans cet épisode : extraits du débat télévisé entre Kamala Harris et Donald Trump le 10 septembre 2024. Cet épisode a été publié le 14 novembre 2024.<br /><br />---<br />Pour soutenir &#34;L&#39;Heure du Monde&#34; et notre rédaction, abonnez-vous sur abopodcast.lemonde.fr</p><p> <br />Hébergé par Audion. Visitez <a href="https://www.audion.fm/fr/privacy-policy" rel="nofollow">https://www.audion.fm/fr/privacy-policy</a> pour plus d’informations.</p>',
        id: "5p6v3tAQlnOoGwZzQ2nUVw",
        images: [
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8ab697f2839a71364e538b49ae",
            width: 640,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1fb697f2839a71364e538b49ae",
            width: 300,
          },
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68db697f2839a71364e538b49ae",
            width: 64,
          },
        ],
        is_externally_hosted: false,
        is_playable: true,
        language: "fr",
        languages: ["fr"],
        name: "Élection de Donald Trump : pourquoi Kamala Harris a-t-elle perdu ?",
        release_date: "2024-11-14",
        release_date_precision: "day",
        resume_point: {
          fully_played: false,
          resume_position_ms: 0,
        },
        show: {
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          copyrights: [],
          description:
            'Tous les matins du lundi au vendredi, Jean-Guillaume Santi reçoit un journaliste de la rédaction du "Monde" pour bien comprendre les enjeux de l\'actualité.  Hébergé par Audion. Visitez https://www.audion.fm/fr/privacy-policy pour plus d’informations.',
          explicit: false,
          external_urls: {
            spotify: "https://open.spotify.com/show/2ceI3IzPwHJywfQTAtrQSI",
          },
          href: "https://api.spotify.com/v1/shows/2ceI3IzPwHJywfQTAtrQSI",
          html_description:
            '<p>Tous les matins du lundi au vendredi, Jean-Guillaume Santi reçoit un journaliste de la rédaction du &#34;Monde&#34; pour bien comprendre les enjeux de l&#39;actualité. </p><p> <br />Hébergé par Audion. Visitez <a href="https://www.audion.fm/fr/privacy-policy" rel="nofollow">https://www.audion.fm/fr/privacy-policy</a> pour plus d’informations.</p>',
          id: "2ceI3IzPwHJywfQTAtrQSI",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab6765630000ba8a1cb22a1c032b8a65a745d497",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67656300005f1f1cb22a1c032b8a65a745d497",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab6765630000f68d1cb22a1c032b8a65a745d497",
              width: 64,
            },
          ],
          is_externally_hosted: false,
          languages: ["fr"],
          media_type: "audio",
          name: "L’Heure du Monde",
          publisher: "Le Monde",
          total_episodes: 877,
          type: "show",
          uri: "spotify:show:2ceI3IzPwHJywfQTAtrQSI",
        },
        type: "episode",
        uri: "spotify:episode:5p6v3tAQlnOoGwZzQ2nUVw",
      },
    },
  ],
};

app.get("/api/userPodcasts", (req, res, next) => {
  res.json(userPodcasts);
});

const userArtists = {
  items: [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/5aigDdW1JMwlIHdOgn8JG6",
      },
      followers: {
        href: null,
        total: 9591,
      },
      genres: ["halifax indie", "psych gaze"],
      href: "https://api.spotify.com/v1/artists/5aigDdW1JMwlIHdOgn8JG6",
      id: "5aigDdW1JMwlIHdOgn8JG6",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb1e4590a2e51c4f72a7476968",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051741e4590a2e51c4f72a7476968",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1781e4590a2e51c4f72a7476968",
          width: 160,
        },
      ],
      name: "The Everywheres",
      popularity: 43,
      type: "artist",
      uri: "spotify:artist:5aigDdW1JMwlIHdOgn8JG6",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/1QAJqy2dA3ihHBFIHRphZj",
      },
      followers: {
        href: null,
        total: 13377275,
      },
      genres: ["ambient pop", "dream pop", "el paso indie", "shoegaze"],
      href: "https://api.spotify.com/v1/artists/1QAJqy2dA3ihHBFIHRphZj",
      id: "1QAJqy2dA3ihHBFIHRphZj",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb0e871e0389b9722cc12a4118",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051740e871e0389b9722cc12a4118",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1780e871e0389b9722cc12a4118",
          width: 160,
        },
      ],
      name: "Cigarettes After Sex",
      popularity: 86,
      type: "artist",
      uri: "spotify:artist:1QAJqy2dA3ihHBFIHRphZj",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/5b5bt4mZQpJMoCRbiQ7diH",
      },
      followers: {
        href: null,
        total: 362228,
      },
      genres: ["australian indie rock"],
      href: "https://api.spotify.com/v1/artists/5b5bt4mZQpJMoCRbiQ7diH",
      id: "5b5bt4mZQpJMoCRbiQ7diH",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb080de26afb71545d9666e2a4",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab67616100005174080de26afb71545d9666e2a4",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f178080de26afb71545d9666e2a4",
          width: 160,
        },
      ],
      name: "Royel Otis",
      popularity: 73,
      type: "artist",
      uri: "spotify:artist:5b5bt4mZQpJMoCRbiQ7diH",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/20oT5LKCdO5vqCSgZ83OsQ",
      },
      followers: {
        href: null,
        total: 50211,
      },
      genres: ["lo-fi beats"],
      href: "https://api.spotify.com/v1/artists/20oT5LKCdO5vqCSgZ83OsQ",
      id: "20oT5LKCdO5vqCSgZ83OsQ",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb6632941f18ac37e864199014",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051746632941f18ac37e864199014",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1786632941f18ac37e864199014",
          width: 160,
        },
      ],
      name: "Mayaewk",
      popularity: 45,
      type: "artist",
      uri: "spotify:artist:20oT5LKCdO5vqCSgZ83OsQ",
    },
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/73mSg0dykFyhvU96tb5xQV",
      },
      followers: {
        href: null,
        total: 557976,
      },
      genres: [],
      href: "https://api.spotify.com/v1/artists/73mSg0dykFyhvU96tb5xQV",
      id: "73mSg0dykFyhvU96tb5xQV",
      images: [
        {
          height: 640,
          url: "https://i.scdn.co/image/ab6761610000e5eb5211c31290a0d915d4ee2225",
          width: 640,
        },
        {
          height: 320,
          url: "https://i.scdn.co/image/ab676161000051745211c31290a0d915d4ee2225",
          width: 320,
        },
        {
          height: 160,
          url: "https://i.scdn.co/image/ab6761610000f1785211c31290a0d915d4ee2225",
          width: 160,
        },
      ],
      name: "Hermanos Gutiérrez",
      popularity: 70,
      type: "artist",
      uri: "spotify:artist:73mSg0dykFyhvU96tb5xQV",
    },
  ],
  total: 338,
  limit: 5,
  offset: 0,
  href: "https://api.spotify.com/v1/me/top/artists?limit=5&locale=fr,fr-FR;q%3D0.8,en-US;q%3D0.5,en;q%3D0.3",
  next: "https://api.spotify.com/v1/me/top/artists?offset=5&limit=5&locale=fr,fr-FR;q%3D0.8,en-US;q%3D0.5,en;q%3D0.3",
  previous: null,
};

app.get("/api/userArtists", (req, res, next) => {
  res.json(userArtists);
});

const userConcerts = {
  href: "https://api.spotify.com/v1/me/shows?offset=0&limit=5&locale=fr,fr-FR;q%3D0.8,en-US;q%3D0.5,en;q%3D0.3",
  items: [
    {
      added_at: "2022-05-05T06:23:16Z",
      show: {
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        copyrights: [],
        description:
          "Découvrez Batman Autopsie en plusieurs langues ici. Un tueur en série connu sous le nom du Moissonneur terrorise Gotham City, mais Batman est aux abonnés absents. Et pour cause, Bruce Wayne semble avoir oublié qu’il est l’homme chauve-souris. Il est désormais médecin légiste. Alors qu'il est chargé d’autopsier la dernière victime du Moissonneur, il est violemment attaqué par le tueur lui-même. Suite à cette agression, l'obsession de Bruce pour le Moissonneur, le consume et le Dr Thomas Wayne, directeur de l'hôpital de Gotham City, ordonne à son fils d’aller consulter un étrange psychiatre, le Dr Hunter, tandis que l’absence de Batman pousse Barbara Gordon à solliciter l’aide du second meilleur détective de Gotham : Le Sphinx.Batman Autopsie est une série audio Spotify Original, produite par Spotify Studios en association avec Une Fille Productions. C’est une adaptation de la production originale américaine \"Batman Unburied\", produite par Phantom Four et Blue Ribbon Content en association avec Wolf at the Door, et créé par David S. Goyer.Batman Autopsie a été réalisée par Douglas Attal.Avec Dali Benssalah dans le rôle de Bruce WayneAvec également :Julia Piaton dans le rôle de Barbara GordonAndré Dussollier dans le rôle de Dr HunterLaurent Stocker de la Comédie Française dans le rôle du SphinxAnaïde Rozam dans le rôle de KellAna Girardot dans le rôle de Vicky ValeThibault de Montalembert dans le rôle de Thomas WayneShirine Boutella dans le rôle de Renee MontoyaSam Karmann dans le rôle d’AlfredChristophe Montenez de la Comédie Française dans le rôle du MoissonneurGuy Lecluyse dans le rôle d’Arnold FlassAvec la participation d'Amira Casar dans le rôle de Martha Wayne",
        explicit: true,
        external_urls: {
          spotify: "https://open.spotify.com/show/6Rzc1GJgMmqX8INl6MmuXc",
        },
        href: "https://api.spotify.com/v1/shows/6Rzc1GJgMmqX8INl6MmuXc",
        html_description:
          '<p><a href="https://open.spotify.com/genre/0JQ5DAqbMKFynr8fSIPvz8" rel="nofollow">Découvrez Batman Autopsie en plusieurs langues ici</a>. Un tueur en série connu sous le nom du Moissonneur terrorise Gotham City, mais Batman est aux abonnés absents. Et pour cause, Bruce Wayne semble avoir oublié qu’il est l’homme chauve-souris. Il est désormais médecin légiste. Alors qu&#39;il est chargé d’autopsier la dernière victime du Moissonneur, il est violemment attaqué par le tueur lui-même. Suite à cette agression, l&#39;obsession de Bruce pour le Moissonneur, le consume et le Dr Thomas Wayne, directeur de l&#39;hôpital de Gotham City, ordonne à son fils d’aller consulter un étrange psychiatre, le Dr Hunter, tandis que l’absence de Batman pousse Barbara Gordon à solliciter l’aide du second meilleur détective de Gotham : Le Sphinx.</p><p><br /></p><p>Batman Autopsie est une série audio Spotify Original, produite par Spotify Studios en association avec Une Fille Productions. C’est une adaptation de la production originale américaine &#34;Batman Unburied&#34;, produite par Phantom Four et Blue Ribbon Content en association avec Wolf at the Door, et créé par David S. Goyer.</p><p><br /></p><p>Batman Autopsie a été réalisée par Douglas Attal.</p><p>Avec Dali Benssalah dans le rôle de Bruce Wayne</p><p>Avec également :</p><p>Julia Piaton dans le rôle de Barbara Gordon</p><p>André Dussollier dans le rôle de Dr Hunter</p><p>Laurent Stocker de la Comédie Française dans le rôle du Sphinx</p><p>Anaïde Rozam dans le rôle de Kell</p><p>Ana Girardot dans le rôle de Vicky Vale</p><p>Thibault de Montalembert dans le rôle de Thomas Wayne</p><p>Shirine Boutella dans le rôle de Renee Montoya</p><p>Sam Karmann dans le rôle d’Alfred</p><p>Christophe Montenez de la Comédie Française dans le rôle du Moissonneur</p><p>Guy Lecluyse dans le rôle d’Arnold Flass</p><p>Avec la participation d&#39;Amira Casar dans le rôle de Martha Wayne</p>',
        id: "6Rzc1GJgMmqX8INl6MmuXc",
        images: [
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68dc2f8a668cef5fc22b2a0956d",
            width: 64,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1fc2f8a668cef5fc22b2a0956d",
            width: 300,
          },
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8ac2f8a668cef5fc22b2a0956d",
            width: 640,
          },
        ],
        is_externally_hosted: false,
        languages: ["fr"],
        media_type: "audio",
        name: "Batman Autopsie",
        publisher: "Warner Bros. / Spotify Studios ",
        total_episodes: 11,
        type: "show",
        uri: "spotify:show:6Rzc1GJgMmqX8INl6MmuXc",
      },
    },
    {
      added_at: "2021-07-19T07:52:21Z",
      show: {
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        copyrights: [],
        description:
          'Tous les matins du lundi au vendredi, Jean-Guillaume Santi reçoit un journaliste de la rédaction du "Monde" pour bien comprendre les enjeux de l\'actualité.  Hébergé par Audion. Visitez https://www.audion.fm/fr/privacy-policy pour plus d’informations.',
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/show/2ceI3IzPwHJywfQTAtrQSI",
        },
        href: "https://api.spotify.com/v1/shows/2ceI3IzPwHJywfQTAtrQSI",
        html_description:
          '<p>Tous les matins du lundi au vendredi, Jean-Guillaume Santi reçoit un journaliste de la rédaction du &#34;Monde&#34; pour bien comprendre les enjeux de l&#39;actualité. </p><p> <br />Hébergé par Audion. Visitez <a href="https://www.audion.fm/fr/privacy-policy" rel="nofollow">https://www.audion.fm/fr/privacy-policy</a> pour plus d’informations.</p>',
        id: "2ceI3IzPwHJywfQTAtrQSI",
        images: [
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68d1cb22a1c032b8a65a745d497",
            width: 64,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1f1cb22a1c032b8a65a745d497",
            width: 300,
          },
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8a1cb22a1c032b8a65a745d497",
            width: 640,
          },
        ],
        is_externally_hosted: false,
        languages: ["fr"],
        media_type: "audio",
        name: "L’Heure du Monde",
        publisher: "Le Monde",
        total_episodes: 877,
        type: "show",
        uri: "spotify:show:2ceI3IzPwHJywfQTAtrQSI",
      },
    },
    {
      added_at: "2020-09-29T12:55:14Z",
      show: {
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        copyrights: [],
        description:
          "Le podcast La Sueur, toujours sur le front, animé par Guillaume & Rust. On parle MMA, UFC, boxe, arts martiaux et autres sports de combat la plupart du temps mais on ne s'interdit par quelques excursions ici et là.🎧Pour écouter le podcast en audio sur toutes les plateformes, www.direct.me/lasueur (http://www.direct.me/lasueur). 🎧 Hébergé par Acast. Visitez acast.com/privacy pour plus d'informations.",
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/show/4yxsP0n5oVYB6mBd2irJyJ",
        },
        href: "https://api.spotify.com/v1/shows/4yxsP0n5oVYB6mBd2irJyJ",
        html_description:
          '<p>Le podcast La Sueur, toujours sur le front, animé par Guillaume &amp; Rust. On parle MMA, UFC, boxe, arts martiaux et autres sports de combat la plupart du temps mais on ne s&#39;interdit par quelques excursions ici et là.</p><br /><p>&#x1f3a7;Pour écouter le podcast en audio sur toutes les plateformes, www.direct.me/lasueur (http://www.direct.me/lasueur). &#x1f3a7;</p><br /><p> Hébergé par Acast. Visitez <a href="https://acast.com/privacy" rel="nofollow">acast.com/privacy</a> pour plus d&#39;informations.</p>',
        id: "4yxsP0n5oVYB6mBd2irJyJ",
        images: [
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68d08aaa9da1ea93145825eb0b0",
            width: 64,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1f08aaa9da1ea93145825eb0b0",
            width: 300,
          },
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8a08aaa9da1ea93145825eb0b0",
            width: 640,
          },
        ],
        is_externally_hosted: false,
        languages: ["fr"],
        media_type: "audio",
        name: "La Sueur",
        publisher: "La Sueur",
        total_episodes: 1713,
        type: "show",
        uri: "spotify:show:4yxsP0n5oVYB6mBd2irJyJ",
      },
    },
    {
      added_at: "2020-09-03T14:19:28Z",
      show: {
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        copyrights: [],
        description:
          "Floodcast, c'est le podcast présenté par Florent Bernard et Adrien Ménielle dans lequel ils invitent des artistes pour discuter de pleins de choses.  Hébergé par Acast. Visitez acast.com/privacy pour plus d'informations.",
        explicit: true,
        external_urls: {
          spotify: "https://open.spotify.com/show/0bmWonDp36VG0OpSYJwJHr",
        },
        href: "https://api.spotify.com/v1/shows/0bmWonDp36VG0OpSYJwJHr",
        html_description:
          'Floodcast, c&#39;est le podcast présenté par Florent Bernard et Adrien Ménielle dans lequel ils invitent des artistes pour discuter de pleins de choses. <br /><p> Hébergé par Acast. Visitez <a href="https://acast.com/privacy" rel="nofollow">acast.com/privacy</a> pour plus d&#39;informations.</p>',
        id: "0bmWonDp36VG0OpSYJwJHr",
        images: [
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68d7436e8e10e39bac66ac48c72",
            width: 64,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1f7436e8e10e39bac66ac48c72",
            width: 300,
          },
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8a7436e8e10e39bac66ac48c72",
            width: 640,
          },
        ],
        is_externally_hosted: false,
        languages: ["fr"],
        media_type: "audio",
        name: "FloodCast",
        publisher: "FloodCast",
        total_episodes: 216,
        type: "show",
        uri: "spotify:show:0bmWonDp36VG0OpSYJwJHr",
      },
    },
    {
      added_at: "2019-02-18T08:13:13Z",
      show: {
        available_markets: [
          "AR",
          "AU",
          "AT",
          "BE",
          "BO",
          "BR",
          "BG",
          "CA",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DK",
          "DO",
          "DE",
          "EC",
          "EE",
          "SV",
          "FI",
          "FR",
          "GR",
          "GT",
          "HN",
          "HK",
          "HU",
          "IS",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MY",
          "MT",
          "MX",
          "NL",
          "NZ",
          "NI",
          "NO",
          "PA",
          "PY",
          "PE",
          "PH",
          "PL",
          "PT",
          "SG",
          "SK",
          "ES",
          "SE",
          "CH",
          "TW",
          "TR",
          "UY",
          "US",
          "GB",
          "AD",
          "LI",
          "MC",
          "ID",
          "JP",
          "TH",
          "VN",
          "RO",
          "IL",
          "ZA",
          "SA",
          "AE",
          "BH",
          "QA",
          "OM",
          "KW",
          "EG",
          "MA",
          "DZ",
          "TN",
          "LB",
          "JO",
          "PS",
          "IN",
          "BY",
          "KZ",
          "MD",
          "UA",
          "AL",
          "BA",
          "HR",
          "ME",
          "MK",
          "RS",
          "SI",
          "KR",
          "BD",
          "PK",
          "LK",
          "GH",
          "KE",
          "NG",
          "TZ",
          "UG",
          "AG",
          "AM",
          "BS",
          "BB",
          "BZ",
          "BT",
          "BW",
          "BF",
          "CV",
          "CW",
          "DM",
          "FJ",
          "GM",
          "GE",
          "GD",
          "GW",
          "GY",
          "HT",
          "JM",
          "KI",
          "LS",
          "LR",
          "MW",
          "MV",
          "ML",
          "MH",
          "FM",
          "NA",
          "NR",
          "NE",
          "PW",
          "PG",
          "PR",
          "WS",
          "SM",
          "ST",
          "SN",
          "SC",
          "SL",
          "SB",
          "KN",
          "LC",
          "VC",
          "SR",
          "TL",
          "TO",
          "TT",
          "TV",
          "VU",
          "AZ",
          "BN",
          "BI",
          "KH",
          "CM",
          "TD",
          "KM",
          "GQ",
          "SZ",
          "GA",
          "GN",
          "KG",
          "LA",
          "MO",
          "MR",
          "MN",
          "NP",
          "RW",
          "TG",
          "UZ",
          "ZW",
          "BJ",
          "MG",
          "MU",
          "MZ",
          "AO",
          "CI",
          "DJ",
          "ZM",
          "CD",
          "CG",
          "IQ",
          "LY",
          "TJ",
          "VE",
          "ET",
          "XK",
        ],
        copyrights: [],
        description:
          "ZQSD, c'est le podcast des gens qui ont coulé le magazine Joystick. Il y est question de jeux vidéo consoles (un peu) et PC (surtout), et de temps en temps de pangolins. Pour nous soutenir, retrouvez-nous sur Patreon : https://www.patreon.com/ZQSD !",
        explicit: true,
        external_urls: {
          spotify: "https://open.spotify.com/show/6uuskQPFC0LHPrVwiWDdTC",
        },
        href: "https://api.spotify.com/v1/shows/6uuskQPFC0LHPrVwiWDdTC",
        html_description:
          "ZQSD, c&#39;est le podcast des gens qui ont coulé le magazine Joystick. Il y est question de jeux vidéo consoles (un peu) et PC (surtout), et de temps en temps de pangolins. Pour nous soutenir, retrouvez-nous sur Patreon : https://www.patreon.com/ZQSD !",
        id: "6uuskQPFC0LHPrVwiWDdTC",
        images: [
          {
            height: 64,
            url: "https://i.scdn.co/image/ab6765630000f68d405e6a0bd6aedf16dbdb43eb",
            width: 64,
          },
          {
            height: 300,
            url: "https://i.scdn.co/image/ab67656300005f1f405e6a0bd6aedf16dbdb43eb",
            width: 300,
          },
          {
            height: 640,
            url: "https://i.scdn.co/image/ab6765630000ba8a405e6a0bd6aedf16dbdb43eb",
            width: 640,
          },
        ],
        is_externally_hosted: false,
        languages: ["fr-FR"],
        media_type: "audio",
        name: "ZQSD",
        publisher: "ZQSD.fr",
        total_episodes: 155,
        type: "show",
        uri: "spotify:show:6uuskQPFC0LHPrVwiWDdTC",
      },
    },
  ],
  limit: 5,
  next: null,
  offset: 0,
  previous: null,
  total: 5,
};

app.get("/api/userConcerts", (req, res, next) => {
  res.json(userConcerts);
});

// Get the port from the environment variables
const port = process.env.APP_PORT;

// Start the server and listen on the specified port
app
  .listen(port, () => {
    console.info(`Server is listening on port ${port}`);
  })
  .on("error", (err: Error) => {
    console.error("Error:", err.message);
  });
